name: My First Workflow
on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest    
    steps:
    #login to docker
    - name: Login to Docker Hub
      uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
    #build and push
    - name: build and push
      uses: docker/build-push-action@v3
        with:
          push: true
          tags: wheresmyweekend/randnum:${{ github.ref_name }}
    #notify
    - name: Send custom JSON data to Slack workflow
      id: slack
      uses: slackapi/slack-github-action@v1.18.0
  with:
    # For posting a rich message using Block Kits
    payload: |
      {
        "type": "mrkdwn",
        "text": "Name: ${{ secrets.NAME }}\n
                  Matriculation: ${{ secrets.NUS_MATRIC_NUMBER }}\n
                  Email: ${{ secrets.NUS_EMAIL }}\n
                  Repo: ${{ github.repositoryUrl }}\n
                  Image name: ${{ secrets.DOCKER_IMAGE_NAME }}:${{ github.ref_name }}\n
                  Image url: ${{ secrets.DOCKER_IMAGE_URL}}"
        
      }
  env:
    SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
    SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK